using System;
using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;

namespace WPZ0325.EasyDocument
{
    /// <summary>
    /// 章节平滑滚动缓动类型
    /// </summary>
    public enum EnEaseType
    {
        Linear = 0,
        EaseIn = 1,
        EaseOut = 2,
        EaseInOut = 3,
    }

    /// <summary>
    /// 章节按钮生成模式：手动配置（拖入按钮绑定列表）/ 自动配置（拖入预制体+root 自动生成并绑定）
    /// </summary>
    public enum EnChapterButtonMode
    {
        Manual = 0,
        Auto = 1,
    }

    /// <summary>
    /// 章节导航器：挂载于含 ScrollRect 的对象上，提供按章节平滑滚动定位能力。
    /// 自动订阅 EasyDocumentController 的生成/清理事件刷新章节索引。
    /// ExecuteAlways：编辑器非播放模式下也订阅事件，保证面板章节索引与生成按钮联动。
    /// </summary>
    [ExecuteAlways]
    [RequireComponent(typeof(ScrollRect))]
    public class EasyDocumentChapterNavigator : MonoBehaviour
    {
        /// <summary>
        /// 章节信息
        /// </summary>
        [Serializable]
        public class ChapterInfo
        {
            /// <summary>
            /// 章节标题文本
            /// </summary>
            public string Title;

            /// <summary>
            /// 章节标题级别（TITLE_1~TITLE_4）
            /// </summary>
            public EnEasyDocumentElementType Level;

            /// <summary>
            /// 章节块挂载点
            /// </summary>
            public RectTransform BlockRect;
        }

        /// <summary>
        /// 章节按钮绑定：用户拖入的章节跳转按钮，顺序对应章节 index
        /// </summary>
        [Serializable]
        public class ChapterButtonBinding
        {
            /// <summary>
            /// 章节跳转按钮（可空，空则跳过绑定）
            /// </summary>
            public Button ButtonRef;
        }

        #region 序列化字段

        [Tooltip("EasyDocumentController 引用（用于订阅文档生成/清理事件）")]
        [SerializeField] EasyDocumentController _controller;
        [Tooltip("平滑滚动时长（秒）")]
        [SerializeField] float _smoothDuration = 0.5f;
        [Tooltip("平滑滚动缓动类型")]
        [SerializeField] EnEaseType _smoothType = EnEaseType.EaseInOut;
        [Tooltip("章节跳转按钮绑定列表（顺序对应章节 index，可空）")]
        [SerializeField] List<ChapterButtonBinding> _chapterButtonBindings = new List<ChapterButtonBinding>();

        [Header("------章节按钮生成模式------")]
        [Tooltip("手动配置：拖入按钮绑定列表；自动配置：拖入预制体+root，自动生成并绑定")]
        [SerializeField] EnChapterButtonMode _buttonMode = EnChapterButtonMode.Manual;
        [Tooltip("自动模式：章节按钮预制体（可空，空则自动构建 Image+Button+TMP）")]
        [SerializeField] GameObject _prefabChapterButton;
        [Tooltip("自动模式：按钮生成的挂载 root（建议放在 Content 之外，避免被文档清空逻辑销毁）")]
        [SerializeField] RectTransform _buttonContainer;
        [Tooltip("自动模式：是否生成 1 级标题按钮")]
        [SerializeField] bool _generateTitle1 = true;
        [Tooltip("自动模式：是否生成 2 级标题按钮")]
        [SerializeField] bool _generateTitle2 = true;
        [Tooltip("自动模式：是否生成 3 级标题按钮")]
        [SerializeField] bool _generateTitle3 = true;
        [Tooltip("自动模式：是否生成 4 级标题按钮")]
        [SerializeField] bool _generateTitle4 = true;

        #endregion

        #region 私有字段

        private ScrollRect _scrollRect;
        private readonly List<ChapterInfo> _chapters = new List<ChapterInfo>();
        private readonly Dictionary<Button, UnityAction> _buttonActions = new Dictionary<Button, UnityAction>();
        private IEnumerator _scrollCoroutine;
        private readonly List<GameObject> _autoGeneratedButtons = new List<GameObject>();
        private bool _refreshPending;

        #endregion

        #region 属性

        /// <summary>
        /// 章节按钮生成模式（运行时切换会立即重建/清理对应按钮）
        /// </summary>
        public EnChapterButtonMode ButtonMode
        {
            get
            {
                return _buttonMode;
            }
            set
            {
                if (_buttonMode == value) return;
                _buttonMode = value;

                if (Application.isPlaying)
                {
                    UnbindAllButtons();
                    RefreshChapters();
                    BindChapterButtons();
                }
                else
                {
                    RefreshChapters();
                }
            }
        }

        #endregion

        #region 生命周期

        private void Awake()
        {
            _scrollRect = this.GetComponent<ScrollRect>();
        }

        private void OnEnable()
        {
            if (_controller != null)
            {
                _controller.OnDocumentGenerated.AddListener(RefreshChapters);
                _controller.OnDocumentCleared.AddListener(ClearChapters);
            }

            RefreshChapters();

            if (Application.isPlaying)
            {
                BindChapterButtons();
            }
        }

        private void OnDisable()
        {
            if (_controller != null)
            {
                _controller.OnDocumentGenerated.RemoveListener(RefreshChapters);
                _controller.OnDocumentCleared.RemoveListener(ClearChapters);
            }

            if (Application.isPlaying)
            {
                UnbindAllButtons();
            }
        }

        /// <summary>
        /// 移除全部按钮监听（OnDisable 或清空索引时调用）
        /// </summary>
        private void UnbindAllButtons()
        {
            foreach (KeyValuePair<Button, UnityAction> pair in _buttonActions)
            {
                if (pair.Key != null)
                {
                    pair.Key.onClick.RemoveListener(pair.Value);
                }
            }
            _buttonActions.Clear();
        }

        /// <summary>
        /// 编辑器下 Inspector 参数变化（含模式切换）时自动重建按钮。
        /// OnValidate 回调中禁止一切销毁操作（DestroyImmediate 与 Destroy 均不允许），
        /// 因此将刷新延迟到帧末 delayCall 执行（此时可安全使用 DestroyImmediate）
        /// </summary>
        private void OnValidate()
        {
            if (Application.isPlaying) return;
            if (_scrollRect == null)
            {
                _scrollRect = this.GetComponent<ScrollRect>();
            }

#if UNITY_EDITOR
            if (_refreshPending) return;
            _refreshPending = true;
            UnityEditor.EditorApplication.delayCall += DelayedRefresh;
#endif
        }

        /// <summary>
        /// 帧末延迟刷新（延迟到 OnValidate 上下文之外，可安全销毁/重建按钮）
        /// </summary>
        private void DelayedRefresh()
        {
            _refreshPending = false;
            RefreshChapters();
        }

        #endregion

        #region 章节索引

        /// <summary>
        /// 章节列表（只读，供编辑器面板展示层级结构）
        /// </summary>
        public IReadOnlyList<ChapterInfo> Chapters
        {
            get
            {
                return _chapters;
            }
        }

        /// <summary>
        /// 扫描 Content 下所有 TITLE_1~TITLE_4 文本块，重建章节索引
        /// （文档生成事件触发时自动调用，也可手动调用）
        /// </summary>
        public void RefreshChapters()
        {
            _chapters.Clear();
            ClearAutoButtons();
            if (_scrollRect == null || _scrollRect.content == null) return;

            Canvas.ForceUpdateCanvases();

            EasyDocumentElementUI_Text[] textBlocks = _scrollRect.content.GetComponentsInChildren<EasyDocumentElementUI_Text>(true);
            if (textBlocks == null || textBlocks.Length == 0) return;

            for (int i = 0; i < textBlocks.Length; i++)
            {
                EasyDocumentElementUI_Text textBlock = textBlocks[i];
                EnEasyDocumentElementType level = textBlock.ElementType;
                if (level != EnEasyDocumentElementType.TITLE_1 &&
                    level != EnEasyDocumentElementType.TITLE_2 &&
                    level != EnEasyDocumentElementType.TITLE_3 &&
                    level != EnEasyDocumentElementType.TITLE_4)
                {
                    continue;
                }

                ChapterInfo info = new ChapterInfo();
                info.Level = level;
                info.BlockRect = textBlock.transform as RectTransform;

                TextMeshProUGUI tmpText = textBlock.GetComponent<TextMeshProUGUI>();
                info.Title = tmpText != null ? tmpText.text : string.Empty;

                _chapters.Add(info);
            }

            if (_buttonMode == EnChapterButtonMode.Auto)
            {
                RebuildAutoButtons();
            }
            else
            {
                SyncBindingList();
            }
        }

        /// <summary>
        /// 同步绑定列表长度与章节数量一致（保留已拖入的按钮引用，尾部补齐/裁剪）
        /// </summary>
        private void SyncBindingList()
        {
            while (_chapterButtonBindings.Count < _chapters.Count)
            {
                _chapterButtonBindings.Add(new ChapterButtonBinding());
            }
            while (_chapterButtonBindings.Count > _chapters.Count)
            {
                _chapterButtonBindings.RemoveAt(_chapterButtonBindings.Count - 1);
            }
        }

        /// <summary>
        /// 清空章节索引与按钮绑定（文档清理事件触发时自动调用，彻底清除后重新生成）
        /// </summary>
        private void ClearChapters()
        {
            _chapters.Clear();
            _chapterButtonBindings.Clear();
            UnbindAllButtons();
            ClearAutoButtons();
            if (_buttonMode == EnChapterButtonMode.Auto)
            {
                ClearAutoButtonContainer();
            }
        }

        /// <summary>
        /// 为章节绑定列表中的按钮添加点击监听：有引用则绑定 ScrollToChapter(index)，无引用则跳过
        /// 仅手动配置模式生效（自动模式运行时互斥）
        /// </summary>
        private void BindChapterButtons()
        {
            if (_buttonMode != EnChapterButtonMode.Manual) return;

            for (int i = 0; i < _chapterButtonBindings.Count; i++)
            {
                ChapterButtonBinding binding = _chapterButtonBindings[i];
                if (binding == null || binding.ButtonRef == null) continue;
                if (_buttonActions.ContainsKey(binding.ButtonRef)) continue;

                int capturedIndex = i;
                UnityAction action = () => ScrollToChapter(capturedIndex);
                binding.ButtonRef.onClick.AddListener(action);
                _buttonActions.Add(binding.ButtonRef, action);
            }
        }

        #endregion

        #region 自动配置按钮

        /// <summary>
        /// 自动配置模式：清空容器全部子对象后，按级别开关过滤章节并重新生成、绑定按钮
        /// 自动模式下容器由本组件全权管理，任何残留（含历史异常遗留的孤儿按钮）都会在此清空，杜绝累积
        /// </summary>
        private void RebuildAutoButtons()
        {
            if (_buttonContainer == null)
            {
                Debug.LogWarning("[EasyDocument] 自动配置模式需要指定 _buttonContainer（按钮生成挂载点）");
                return;
            }

            ClearAutoButtonContainer();
            _autoGeneratedButtons.Clear();
            EnsureContainerLayout();

            for (int i = 0; i < _chapters.Count; i++)
            {
                ChapterInfo info = _chapters[i];
                if (!IsTitleEnabled(info.Level)) continue;

                GameObject buttonObj = CreateAutoButton(info);
                if (buttonObj == null) continue;

                _autoGeneratedButtons.Add(buttonObj);
                if (Application.isPlaying)
                {
                    BindAutoButton(buttonObj, i);
                }
            }
        }

        /// <summary>
        /// 标题级别开关过滤：仅生成的级别返回 true
        /// </summary>
        /// <param name="level"></param>
        /// <returns></returns>
        private bool IsTitleEnabled(EnEasyDocumentElementType level)
        {
            switch (level)
            {
                case EnEasyDocumentElementType.TITLE_1:
                    return _generateTitle1;
                case EnEasyDocumentElementType.TITLE_2:
                    return _generateTitle2;
                case EnEasyDocumentElementType.TITLE_3:
                    return _generateTitle3;
                case EnEasyDocumentElementType.TITLE_4:
                    return _generateTitle4;
                default:
                    return false;
            }
        }

        /// <summary>
        /// 创建章节按钮：优先实例化预制体；未配置时自动构建 Image+Button+TMP
        /// 任一步骤失败（如编辑器下 TMP 字体资源未就绪）均不会中断整体生成，失败按钮即时销毁避免残留
        /// </summary>
        /// <param name="info"></param>
        /// <returns></returns>
        private GameObject CreateAutoButton(ChapterInfo info)
        {
            GameObject buttonObj = null;
            try
            {
                if (_prefabChapterButton != null)
                {
                    buttonObj = Instantiate(_prefabChapterButton, _buttonContainer);
                }
                else
                {
                    buttonObj = new GameObject("ChapterButton", typeof(RectTransform));
                    buttonObj.transform.SetParent(_buttonContainer, false);

                    Image image = buttonObj.GetComponent<Image>();
                    if (image == null)
                    {
                        image = buttonObj.AddComponent<Image>();
                    }
                    image.color = new Color(0.78f, 0.82f, 0.86f, 1.0f);
                }

                Button button = buttonObj.GetComponent<Button>();
                if (button == null)
                {
                    button = buttonObj.AddComponent<Button>();
                }

                TextMeshProUGUI tmpText = buttonObj.GetComponent<TextMeshProUGUI>();
                if (tmpText == null)
                {
                    // 根对象无法获取/添加 TMP（如预制体挂的是 3D 版 TextMeshPro 与 TextMeshProUGUI 互斥），
                    // 在子对象上创建文本，保证任意预制体结构都能生成按钮
                    GameObject textObj = new GameObject("Text", typeof(RectTransform));
                    textObj.transform.SetParent(buttonObj.transform, false);
                    tmpText = textObj.AddComponent<TextMeshProUGUI>();
                }

                // 仅当默认字体有效时才手动指定字体；TMP 3.0.6 font setter 内部无空值防护，
                // 编辑器下字体资源未就绪时可能抛异常，捕获后交由 TMP 组件自身 Awake 兜底加载
                TMP_FontAsset fontAsset = EasyDocumentElementUI_Text.GetFontBySetting(null);
                if (fontAsset != null)
                {
                    try
                    {
                        tmpText.font = fontAsset;
                    }
                    catch (Exception)
                    {
                        // ignore：TMP 组件会自行加载默认字体
                    }
                }
                tmpText.fontSize = 18.0f;
                tmpText.color = Color.black;
                tmpText.alignment = TextAlignmentOptions.Left;
                tmpText.raycastTarget = false;
                tmpText.text = info.Title ?? string.Empty;

                return buttonObj;
            }
            catch (Exception e)
            {
                Debug.LogError($"[EasyDocument] 创建章节按钮失败:{info.Title} ,error:{e.Message}");
                DestroyObject(buttonObj);
                return null;
            }
        }

        /// <summary>
        /// 为自动生成的按钮绑定点击跳转（chapterIndex 为章节真实 index，非按钮列表下标）
        /// </summary>
        /// <param name="buttonObj"></param>
        /// <param name="chapterIndex"></param>
        private void BindAutoButton(GameObject buttonObj, int chapterIndex)
        {
            Button button = buttonObj.GetComponent<Button>();
            if (button == null) return;
            button.onClick.AddListener(() => ScrollToChapter(chapterIndex));
        }

        /// <summary>
        /// 销毁全部自动生成的按钮：运行时用 Destroy（帧末延迟销毁），编辑器下用 DestroyImmediate（立即销毁）
        /// </summary>
        private void ClearAutoButtons()
        {
            for (int i = 0; i < _autoGeneratedButtons.Count; i++)
            {
                DestroyObject(_autoGeneratedButtons[i]);
            }
            _autoGeneratedButtons.Clear();
        }

        /// <summary>
        /// 清空按钮容器下全部子对象（自动模式下容器由本组件全权管理）
        /// 用于清除历史异常遗留的孤儿按钮，防止累积
        /// </summary>
        private void ClearAutoButtonContainer()
        {
            if (_buttonContainer == null) return;
            for (int i = _buttonContainer.childCount - 1; i >= 0; i--)
            {
                DestroyObject(_buttonContainer.GetChild(i).gameObject);
            }
        }

        /// <summary>
        /// 销毁对象：运行时用 Destroy（帧末延迟销毁），编辑器下用 DestroyImmediate（立即销毁）。
        /// 注意：任何调用必须发生在非 OnValidate/物理/动画/渲染回调上下文（销毁前已通过延迟刷新规避）
        /// </summary>
        /// <param name="obj"></param>
        private void DestroyObject(GameObject obj)
        {
            if (obj == null) return;
            if (Application.isPlaying)
            {
                Destroy(obj);
            }
            else
            {
                DestroyImmediate(obj);
            }
        }

        /// <summary>
        /// 按钮容器补齐布局：仅当容器没有任何 LayoutGroup 时，自动添加 VerticalLayoutGroup + ContentSizeFitter（平铺）
        /// 已有 GridLayoutGroup/HorizontalLayoutGroup 等自定义布局时不干预
        /// </summary>
        private void EnsureContainerLayout()
        {
            if (_buttonContainer == null) return;
            if (_buttonContainer.GetComponent<LayoutGroup>() != null) return;

            VerticalLayoutGroup vlg = _buttonContainer.GetComponent<VerticalLayoutGroup>();
            if (vlg == null)
            {
                vlg = _buttonContainer.gameObject.AddComponent<VerticalLayoutGroup>();
            }
            vlg.childControlWidth = true;
            vlg.childControlHeight = true;
            vlg.childForceExpandWidth = true;
            vlg.childForceExpandHeight = false;

            ContentSizeFitter csf = _buttonContainer.GetComponent<ContentSizeFitter>();
            if (csf == null)
            {
                csf = _buttonContainer.gameObject.AddComponent<ContentSizeFitter>();
            }
            csf.verticalFit = ContentSizeFitter.FitMode.PreferredSize;
            csf.horizontalFit = ContentSizeFitter.FitMode.Unconstrained;
        }

        #endregion

        #region 滚动

        /// <summary>
        /// 按章节序号滚动到对应章节（从 0 开始）
        /// </summary>
        /// <param name="chapterIndex">章节序号</param>
        /// <param name="onFinished">滚动完成回调</param>
        public void ScrollToChapter(int chapterIndex, Action onFinished = null)
        {
            if (chapterIndex < 0 || chapterIndex >= _chapters.Count)
            {
                Debug.LogWarning($"[EasyDocument] 章节序号越界:{chapterIndex}");
                onFinished?.Invoke();
                return;
            }

            ScrollToRect(_chapters[chapterIndex].BlockRect, onFinished);
        }

        /// <summary>
        /// 按标题模糊匹配滚动到对应章节（互相包含即命中，如传入“第一章”匹配“第一章 简介”）
        /// </summary>
        /// <param name="chapterTitle">章节标题关键字</param>
        /// <param name="onFinished">滚动完成回调</param>
        public void ScrollToChapterByTitle(string chapterTitle, Action onFinished = null)
        {
            if (string.IsNullOrEmpty(chapterTitle))
            {
                onFinished?.Invoke();
                return;
            }

            for (int i = 0; i < _chapters.Count; i++)
            {
                ChapterInfo info = _chapters[i];
                if (info.Title.Contains(chapterTitle) || chapterTitle.Contains(info.Title))
                {
                    ScrollToRect(info.BlockRect, onFinished);
                    return;
                }
            }

            Debug.LogWarning($"[EasyDocument] 未找到章节:{chapterTitle}");
            onFinished?.Invoke();
        }

        /// <summary>
        /// 停止当前滚动并跳转到指定章节块
        /// </summary>
        /// <param name="blockRect"></param>
        /// <param name="onFinished"></param>
        private void ScrollToRect(RectTransform blockRect, Action onFinished)
        {
            if (_scrollRect == null || blockRect == null)
            {
                onFinished?.Invoke();
                return;
            }

            if (_scrollCoroutine != null)
            {
                StopCoroutine(_scrollCoroutine);
                _scrollCoroutine = null;
            }

            float targetNormalized = CalculateTargetNormalized(blockRect);
            _scrollCoroutine = ScrollCoroutine(targetNormalized, onFinished);
            StartCoroutine(_scrollCoroutine);
        }

        /// <summary>
        /// 计算将章节块滚动到视口顶部所需的 verticalNormalizedPosition
        /// </summary>
        /// <param name="blockRect"></param>
        /// <returns></returns>
        private float CalculateTargetNormalized(RectTransform blockRect)
        {
            Canvas.ForceUpdateCanvases();

            RectTransform contentRect = _scrollRect.content;
            RectTransform viewportRect = _scrollRect.viewport;
            if (viewportRect == null)
            {
                viewportRect = this.transform as RectTransform;
            }

            Vector3 blockWorldPos = blockRect.position;
            Vector3 contentLocalPos = contentRect.InverseTransformPoint(blockWorldPos);

            float blockTop = contentLocalPos.y + blockRect.rect.height * (1.0f - blockRect.pivot.y);
            float contentTop = contentRect.rect.height * (1.0f - contentRect.pivot.y);
            float distanceFromTop = Mathf.Max(0.0f, contentTop - blockTop);

            float contentHeight = contentRect.rect.height;
            float viewportHeight = viewportRect.rect.height;
            float maxScroll = Mathf.Max(0.0f, contentHeight - viewportHeight);
            float targetScroll = Mathf.Min(distanceFromTop, maxScroll);

            if (maxScroll <= 0.0f) return 1.0f;
            return 1.0f - targetScroll / maxScroll;
        }

        /// <summary>
        /// 平滑滚动协程
        /// </summary>
        /// <param name="targetNormalized"></param>
        /// <param name="onFinished"></param>
        /// <returns></returns>
        private IEnumerator ScrollCoroutine(float targetNormalized, Action onFinished)
        {
            float startNormalized = _scrollRect.verticalNormalizedPosition;
            float duration = Mathf.Max(0.01f, _smoothDuration);
            float elapsed = 0.0f;

            while (elapsed < duration)
            {
                elapsed += Time.deltaTime;
                float progress = Mathf.Clamp01(elapsed / duration);
                float eased = ApplyEase(progress, _smoothType);
                _scrollRect.verticalNormalizedPosition = Mathf.Lerp(startNormalized, targetNormalized, eased);
                yield return null;
            }

            _scrollRect.verticalNormalizedPosition = targetNormalized;
            onFinished?.Invoke();
        }

        /// <summary>
        /// 应用缓动曲线
        /// </summary>
        /// <param name="progress"></param>
        /// <param name="easeType"></param>
        /// <returns></returns>
        private static float ApplyEase(float progress, EnEaseType easeType)
        {
            switch (easeType)
            {
                case EnEaseType.EaseIn:
                    return progress * progress;
                case EnEaseType.EaseOut:
                    return 1.0f - (1.0f - progress) * (1.0f - progress);
                case EnEaseType.EaseInOut:
                    return progress < 0.5f
                        ? 2.0f * progress * progress
                        : 1.0f - Mathf.Pow(-2.0f * progress + 2.0f, 2.0f) / 2.0f;
                case EnEaseType.Linear:
                default:
                    return progress;
            }
        }

        #endregion
    }
}
